### ISSUE TITLE
[Design] Design artifacts for help text for each element type.

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/forms#270]
## Overview

As a form builder, I would like to provide helpful hints and supplementary instructions to my form applicants, so that I can create a better experience with the form for the applicants and reduce the burden of incorrect/invalid applications for my team.

## Context

*Optional: Any reference material or thoughts we may need for later reference, or assumptions of prior or future work that's out of scope for this story.*

- Check out #256  for suggestions/ideas
- Mocks/options for implementation. ? icon next element is lighter than "green words" ala Suffolk (courtformsonline.org, 209A restraining order)
- We probably don't need a formal UX teardown/prez of existing UI for solving this problem, but a list of links could be handy

## Acceptance Criteria

*Required outcomes of the story*

- [x] Annotated mock-ups that explore how a form builder can add help text
- [x] Annotated mock-ups that explore how a form filler will see help text

## Research Questions

- How do form builders approach help and instruction text
- What patterns are proven, if any, on the form filler side

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ] UX teardown of competing options for adding help text
- [ ] Document and share potential solutions
- [ ] Create and share designs

**Comment by JennyRichards-Flexion** [comment]
9/24 - move to backlog. Pull off the stack whenever we need to work on it.

**Comment by JennyRichards-Flexion** [comment]
Courtformsonline.org might be a good reference

UX teardown of competing options for doing these kinds of things. Little harder to find good references on form builder side. No constellation of options of how this might look. 
Will need to be fleshed out. End goal - presentation of options for form filler and form builder for help text.

**Comment by JennyRichards-Flexion** [comment]
If it makes sense to have more universal artifacts, that's fine too. 

Estimate - 1 week including review and revisions. 
First design ticket on this project.
