### ISSUE TITLE
Add single field component types vertical slice

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/forms#272]
## Overview

As a pardon office form builder, I would like be able to add all the components I need to create the presidential pardon form, so that I don't have to think about validation for common form inputs.

## Context

REFERENCE: USWDS components for address, dob, email, gender, name, phone, pronouns, etc... are in the [user profile components page of the USWDS guidance](https://designsystem.digital.gov/patterns/create-a-user-profile/)

We should also pay good attention to the [USWDS forms controls guidance](https://v1.designsystem.digital.gov/components/form-controls/)

Missing components:

NEEDS DESIGN & SCOPING (these are not ready yet):
- [ ] Signature (discussed with pardon team, eng prototype is here, needs design, is NOT blocking pardon's first draft or user testing)

READY:
- [x] Select (this one is [here](https://designsystem.digital.gov/components/select/) and is necessary for some components below)
- [x] Date (on [user profile page](https://designsystem.digital.gov/patterns/create-a-user-profile/))
- [x] email (on [user profile page](https://designsystem.digital.gov/patterns/create-a-user-profile/)) 
- [x] phone (on [user profile page](https://designsystem.digital.gov/patterns/create-a-user-profile/))
- [x] Social Security number (on [user profile page](https://designsystem.digital.gov/patterns/create-a-user-profile/))
- [x] Gender ID/Sex (on [user profile page](https://designsystem.digital.gov/patterns/create-a-user-profile/))

## Acceptance Criteria

*Required outcomes of the story*

- [ ]

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ]

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by JennyRichards-Flexion** [comment]
Ethan has a good instructive PR that was discussed in the last dev coffee - all the files that need to be touched are discussed there. Might be a good straightforward introduction.

**Comment by JennyRichards-Flexion** [comment]
Started Friday 10/25. Unable to estimate time at this time, roughly 2 days. 
Currently working on Select.
