### ISSUE TITLE
Group pages into hierarchy in form-builder view

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/forms#289]
## Overview

As a form-builder user, I feel overwhelmed by the large number of screens generated via the ingestion of a large pdf and want to be able to quickly navigate to different questions (I am familiar with the questions and with pdf page numbers, but I am not familiar with the new auto-generated page names), so that I can decide to work on a specific part of the form and quickly navigate to it.

As a form-filler user, I feel overwhelmed by the large number of items in the navigation sidebar. I want to feel like the application is doable for me and that I can find my way back to a specific question if I need to change something. (Should we consider only showing page titles the user has interacted with so far? Maybe plus a %age done progress bar?)

## Context

WE WILL GET MORE TRACTION ON THIS AFTER 8/15 PARDON MEETING

- [ ] Review notes from 8/15 pardon meeting

## Acceptance Criteria

*Required outcomes of the story*

- [ ] Form builder users do not feel immediately overwhelmed upon ingest
- [ ] Form builder users can quickly navigate to a question they have in mind that they want to work on
- [ ] Form filler users do not feel overwhelmed from the moment they begin
- [ ] Form filler users can easily get back to a question from a previous page they want to update

## Research Questions

- [ ] How do form builder/filler needs for navigation differ?
- [ ] Are pdf page # references the best navigation "landmarks" for form builders or is there something else that will accomplish quick navigation when beginning work on a draft?

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ] Design mocks new navigation features, including potential enhancements/items to test, focus is on learning
- [ ] Engineering determines how much builder/filler page nav components can/should overlap under the hood
- [ ] Engineering builds minimum testable implementation

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by JennyRichards-Flexion** [comment]
For some reason, I am not able to edit this story (so I can separate it from the Form Filler ticket, #408. Needs to be edited by Jim.
