### ISSUE TITLE
Attachments component skeleton

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/forms#311]
## Overview

NOTE: "Skeleton" here means everything that happens with the exception of pdf generation. Let's get the attachments into placeholder key in the form session object and split actually attaching them to the generated form into another ticket

USER STORY: As a form builder, I would like add a component to my form that allows form filler to upload a document, so that they can attach documents that will show up as supplemental pages at the end of the pdf.

## Context

*Optional: Any reference material or thoughts we may need for later reference, or assumptions of prior or future work that's out of scope for this story.*

- [ ] We should ingest the documents, convert them to pdfs, serialize them, and create a placeholder key in the form session object to store them. Let's not worry about pdf generation in this ticket
- [x] Let's use the [USWDS file input](https://designsystem.digital.gov/components/file-input/) as a guide

## Acceptance Criteria

*Required outcomes of the story*

- [ ] "Skeleton" here means everything that happens with the exception of pdf generation. Let's get the attachments into placeholder key in the form session object and split actually attaching them to the generated form into another ticket
- [x] Form builders should be able to pick "Attach a document" or similar from the components list, for the "skeleton" version let's keep it simple and avoid any optional configuration that doesn't seem 100% necessary
- [x] Form fillers should get the [USWDS file input experience](https://designsystem.digital.gov/components/file-input/)
- [x] Let's stub out the file "input has an error" UI specified above, but leave the bulk of it for the next ticket
- [x] For the skeleton, let's say jpg, png and pdf inputs are sufficient for now, we can progressively enhance

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ] This needs a design ticket for the form builder side, plus any modifications we feel are 100% necessary to the USWDS implementation (hopefully none, but probably won't know this until we test it with Pardon, we can probably test the engineered prototype)

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by JennyRichards-Flexion** [comment]
@danielnaab We think this will probably flow out of the PDF generation work you're doing - and you might be faster to complete this than Ethan given your familiarity with storage.

**Comment by JennyRichards-Flexion** [comment]
This has a front end and back end component, but also a storage component. 
Likely to be a large effort.

**Comment by JennyRichards-Flexion** [comment]
@jimmoffet Do you know why this is in the Blocked status? 
I think it needs additional detail, and then needs to be moved into Backlog or Ready.

**Comment by jimmoffet** [comment]
@JennyRichards-Flexion modified this to exclude the portion that was blocked and moved it to the top of the next sprint

**Comment by JennyRichards-Flexion** [comment]
Ideally this rolls into a separate ticket that is designed around handling the data. 
Even if we're just pushing local file paths for this one. 
It's a new pattern (Dan). 

This *should* be achievable within a 2-week sprint.
