### ISSUE TITLE
[DESIGN] Mock-up Submission Confirmation experience

### ISSUE THREAD

**Issue by JennyRichards-Flexion** [GSA-TTS/forms#357]
## Overview

We need a submission confirmation page. 
This page would provide confirmation to the user that their survey data was captured, but also provide a place for the submitter to download their completed package. 

## Context

From Slack: 
Dan: Earlier in our demo phase, we had a “submission confirmation” pattern that was displayed on the last page of a completed form, that I think we want to resurrect. It’d be the place you’d download your completed package.

My current work is basically “get PDF generation working” so I’m thinking I may put a placeholder in so we have a place to download from. If so, we could prioritize with other form-filler tickets as design work.

The old pattern is still in the codebase, and just needs to be reactivated and maybe some bugs quashed..

**Mockups**
**FORM BUILDER VIEW** Form builder can customize the confirmation message in settings.
- [ ] Section titled "Confirmation page and message"
- [ ] A description with examples of what to include in the message
- [ ] A rich text editor to edit the confirmation message, which appears below the success alert in the filler view
- [ ] (For PDF imports only) A checkbox to include the PDF package button (this should be checked on default)

<img width="1202" alt="Image" src="https://github.com/user-attachments/assets/19934d1a-1374-40ae-ae6d-b1619136fc0e" />

**FORM FILLER VIEW** Form filler can review a confirmation message and review/save a copy of their responses:
- [ ] H1 "Confirmation"
- [ ] H2 "[Form name"]
- [ ] A success alert (with date and confirmation message, if we provide this)
- [ ] Confirmation message (the mockup includes an example of a message with lengthy, detailed next steps)
- [ ] 2 options to download the submitted information (for all forms) and/or the filled PDF (only for PDF imports)
- [ ] A collapsable table of submitted information (the mockup shows example of a repeater and attachment)
- [ ] An option to print a copy of this page

![Image](https://github.com/user-attachments/assets/32e48508-f1d4-4554-b263-702d38863a6a)

## Acceptance Criteria

Displays a message when the survey data has been captured. 
Uncertain what the path would be for submission failures. That may need to be explored here too. 

Also provides the submitter the opportunity to download their complete package. 
May also want to consider how a person navigates back to this page, if/how they get confirmation via email/text/etc. 

- [ ]

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ] Design mock-ups of this experience
- [ ] Engineering re-integration of existing pattern 

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by JennyRichards-Flexion** [comment]
This item requires prioritization and inclusion into the appropriate sprint.

**Comment by JennyRichards-Flexion** [comment]
If we can stick a confirmation page that doesn't break the architecture, that's what we should do as part of this epic. 
Anything more architecturally significant will need to wait for a later Epic.

**Comment by nichole-aquino** [comment]
@ethangardner I made some design changes and updated the mockups in the description following our call on Friday. Let me know if you have any questions or feedback (e.g.how I'm approaching the repeater and attachments in the 'Information you submitted on this form' table). Thanks!
