### ISSUE TITLE
Design artifacts: Splash Page for Forms Platform

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/forms#379]
## Overview

This is a marketing page that needs to concisely tell the story of what our forms platform offers to our audiences: program leadership decision-makers, program office form builders, members of the public who will fill out forms (probably in that order?)

## Context

There is a [figma skeleton](https://www.figma.com/design/ZA7Gf0m7PYR6Aeu0qwIsnf/Jim-Scratch?node-id=29-7&t=i7NDtuh463cqbos1-1) made by Jim as a starting point

## Acceptance Criteria

*Required outcomes of the story*

- [ ]

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ]

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by nichole-aquino** [comment]
Hi @jimmoffet, here are a couple early mocks for the splash page. Building off your skeleton, I've included some placeholder images and have used 10x visual branding for now. Feel free to leave comments in the figma, or we can also chat after our next standup. Thanks!

[Option A](https://www.figma.com/proto/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?node-id=2788-1656&node-type=frame&t=sICjb8rKwWHPIm5s-0&scaling=min-zoom&content-scaling=fixed&page-id=2713%3A24957&starting-point-node-id=2788%3A1656)
[Option B (a bit more condensed)](https://www.figma.com/proto/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?node-id=2788-1566&node-type=frame&t=sICjb8rKwWHPIm5s-0&scaling=min-zoom&content-scaling=fixed&page-id=2713%3A24957&starting-point-node-id=2788%3A1656)

**Comment by nichole-aquino** [comment]
thanks for your feedback @ethangardner  @jimmoffet  – Here's the [revision of Option A](https://www.figma.com/proto/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?node-id=2918-36212&node-type=frame&t=oVIBEj86RfXyWUcs-0&scaling=min-zoom&content-scaling=fixed&page-id=2713%3A24957&starting-point-node-id=2788%3A1566). Happy to continue refining the visual design – for now, I've designed it using USWDS and removed the 10x styles. I've also incorporated a new pattern for the testimonials (thanks for the rec, Ethan!).

**Comment by ethangardner** [comment]
I'll defer to Jim here for final approval, but I think the revised version of Option A looks great!

**Comment by JennyRichards-Flexion** [comment]
@ethangardner I created a new ticket for the work to implement the splash page and we should be able to cover it in backlog refinement for the next sprint (13).

**Comment by jimmoffet** [comment]
Looks good to me!
