### ISSUE TITLE
Design "other" option for radio component

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/forms#401]
## Overview

As a form builder, I would like allow my form filler users to add their own custom option to some radio groups.

## Context

*Optional: Any reference material or thoughts we may need for later reference, or assumptions of prior or future work that's out of scope for this story.*

- [ ] Note, there is no USWDS guidance for this (that Jim is aware of)

## Acceptance Criteria

*Required outcomes of the story*

- [ ] Add config UI to existing radio group edit component that allows form builder to specify "other" as a final option for a radio group
- [ ] When form specifies "other" as final option for radio group, form filler sees a short answer input when they choose this option
- [ ] Need to make sure we handle "required" flag for the radio group as a whole
- [ ] Need to make sure we handle any foreseeable edge cases in Presidential Pardon form

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ]

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*
