### ISSUE TITLE
[Eng] Add information box (accordion) component

### ISSUE THREAD

**Issue by racheledelman** [GSA-TTS/forms#415]
## Overview

As a builder, I would like accordions, so that I can present supplementary information to fillers.

## Context

This uses the [accordion component](https://designsystem.digital.gov/components/accordion/) in USWDS. 

On the build screen, below each component, there is a link to add an "Add supplementary information or instructions":  
![Image](https://github.com/user-attachments/assets/1274c239-abb2-4da4-82c4-2d743a6b9352)

Clicking it adds inputs for the information box title and content:
![Image](https://github.com/user-attachments/assets/03ad2977-e95b-4e1a-a821-84baa2ffeea2)

Clicking the trash icon next to the unit removes it.

---

On the filler side, the accordion appears (closed) below the question it is associated with:
![Image](https://github.com/user-attachments/assets/30031644-5161-4eef-abef-56219813e4f8)

Clicking the accordion opens it and reveals its content:
![Image](https://github.com/user-attachments/assets/ea5bf32a-8fa2-43a4-ab58-e6ff355cd604)

## Acceptance Criteria

*Required outcomes of the story*

- [ ] builders can add accordions to all question types, and the rich text component
- [ ] builders can edit and remove accordions
- [ ] fillers and open and close accordions

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ]

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*
